### PR TITLE
fixed Symfony deprecations

### LINKED ISSUE #928: Document CSRF provider deprecated and new one
from https://github.com/silexphp/Silex/commit/ae4317bb414b1715eecd7694c6dc227cf4c41cc5#commitcomment-5755559

Also it took me a while to figure this out, apparently the default CSRF provider is deprecated, and it also creates a CSRF that is a function of the SESSION ID, which assumes that you even are using sessions, and also that the session ID won't change. Apparently there is a new CSRF provider from Symfony that stores the token as a session variable:

```php
/** Use a CSRF provider that does not depend on the session ID being constant. We change the session ID randomly in middleware/session_lockout.php */
$app['form.csrf_provider'] = $app->share(function ($app) {
    $storage = new Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage($app['session']);
    return new Symfony\Component\Security\Csrf\CsrfTokenManager(null, $storage);
});
```
Should this go in the docs?

cc/ @fabpot @joshribakoff

### PR DESCRIPTION
**Pull request by fabpot**
Brings Symfony 2.7 compatibility to Silex 1.3.

Fixes #928, #1085, #981, #998

Remaining tasks:

 - [x] update docs where needed (hopefully nothing)
 - [x] add notes in the changelog

### CODE REVIEW

**Comment by fabpot** [comment]
This PR is ready for me. Any more comments before the merge?

**Comment by davedevelopment** [comment]
:shipit: for me, I can't see anything awry, but I can't really see the forest for the trees :)

File: src/Silex/Provider/FormServiceProvider.php [hunk 1]
```diff
@@ -104,11 +107,19 @@ public function register(Application $app)
...
+                }
 
-            return new DefaultCsrfProvider($app['form.secret']);
+                return new DefaultCsrfProvider($app['form.secret']);
+            } else {
+                // Symfony 2.4+
+                $storage = isset($app['session']) ? new SessionTokenStorage($app['session']) : new NativeSessionTokenStorage();
+
+                return new CsrfTokenManager(null, $storage);
+            }
```
Comment (stof) [inline src/Silex/Provider/FormServiceProvider.php]: Technically, this is a BC break for people using the ``form.csrf_provider`` on their own, because it changes the class they get.
It might be better to register the CsrfTokenManager as a new service, and providing the BC adapter in ``form.csrf_provider`` (which would trigger a deprecation warning when they get it, but Silex itself would access the new one)

**Comment by mediamonks-robert** [comment]
Can these changes also be merged to master (2.0) branch?
