### PR TITLE
Fixed Session Service Provider registry

### LINKED ISSUE #1342: Something seams wrong in SessionServiceProvider
Hi,

it's not a bug since nothing is broken (yet), but there is something odd on lines 41 and 64 of the SessionServiceProvider (master)

line 41:

    return new Session($app['session.storage']);

the Session `__constructor()` signature is:

    public function __construct(SessionStorageInterface $storage = null, AttributeBagInterface $attributes = null, FlashBagInterface $flashes = null)

line 64:

    return new SessionListener($app, $app['session.attribute_bag'], $app['session.flash_bag']);

the SessionListener `__constructor()` signature is:

    public function __construct(Container $app)

To me it seams like some kind of inversion mistake.

### PR DESCRIPTION
**Pull request by ragboyjr**
The service provider was registering the wrong parameters
to the session listener instead of the actual session class

This fixes #1342 

Signed-off-by: RJ Garcia <rj@bighead.net>

### CODE REVIEW

File: tests/Silex/Tests/Provider/SessionServiceProviderTest.php [hunk 1]
```diff
@@ -104,4 +105,27 @@ public function testWithRoutesThatDoesNotUseSession()
         $client->request('get', '/robots.txt');
         $this->assertEquals('Informations for robots.', $client->getResponse()->getContent());
     }
+
+    /**
+     * Test that you can properly configure the Session class.
+     */
```
Comment (fabpot) [inline tests/Silex/Tests/Provider/SessionServiceProviderTest.php]: I don't think we need this comment.

File: tests/Silex/Tests/Provider/SessionServiceProviderTest.php [hunk 2]
```diff
@@ -104,4 +105,27 @@ public function testWithRoutesThatDoesNotUseSession()
...
+            'session.flash_bag' => $flash,
+            'session.test' => true,
+        ));
+
+        $session = $app['session'];
+
+        $this->assertTrue(
+            $session->getBag('flashes') === $flash &&
+            $session->getBag('attributes') === $attrs
+        );
```
Comment (fabpot) [inline tests/Silex/Tests/Provider/SessionServiceProviderTest.php]: Should be on one line.

**Comment by ragboyjr** [comment]
@fabpot. Those are updated.

out of curiosity with doing conditionals on one line, how would you format a bunch of conditions so that the line isn't so long.

```php
$long_var_name == 1 || $long_var_name_b == 1 || ($long_var_name_2 == 2 || $long_var_name3 == 2) && $one_more_long_var_name ==5 
```

**Comment by fabpot** [comment]
Everyone has a large screen nowadays, so there is no need to cut lines at 80 chars.

File: tests/Silex/Tests/Provider/SessionServiceProviderTest.php [hunk 3]
```diff
@@ -104,4 +105,22 @@ public function testWithRoutesThatDoesNotUseSession()
...
+        $app->register(new SessionServiceProvider(), array(
+            'session.attribute_bag' => $attrs,
+            'session.flash_bag' => $flash,
+            'session.test' => true,
+        ));
+
+        $session = $app['session'];
+
+        $valid = $session->getBag('flashes') === $flash && $session->getBag('attributes') === $attrs;
+        $this->assertTrue($valid);
```
Comment (fabpot) [inline tests/Silex/Tests/Provider/SessionServiceProviderTest.php]: I'd have be more precise like:

```php
$this->assertSame($flash, $session->getBag('flashes');
$this->assertSame($attrs, $session->getBag('attributes');
```

Comment (ragboyjr) [inline tests/Silex/Tests/Provider/SessionServiceProviderTest.php]: No problem, I was just trying to keep the whole 1 assertion per test.

Comment (ragboyjr) [inline tests/Silex/Tests/Provider/SessionServiceProviderTest.php]: updated.

**Comment by fabpot** [comment]
Thank you @ragboyjr.
